Jagu/urls.py
from django.conf.urls import patterns, include, url
from Home import views as HomeViews

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Jagu.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', HomeViews.home),
    url(r'^Home', HomeViews.home),
    url(r'^registro', HomeViews.registro),
    url(r'^login', HomeViews.login),
    url(r'^Monedas', HomeViews.Monedas),
    url(r'^Transacciones', HomeViews.Transacciones),
    url(r'^Categorias', HomeViews.Categorias),
    url(r'^Marcas', HomeViews.Marcas),
    url(r'^Articulos', HomeViews.Articulos),
    url(r'^Pedidos', HomeViews.Pedidos),
    url(r'^Clientes', HomeViews.Clientes),
    url(r'^NuevaVenta', HomeViews.NuevaVenta),
    url(r'^NuevaCompra', HomeViews.NuevaCompra),
    url(r'^NuevoPedido', HomeViews.NuevoPedido),
    url(r'^EditarVenta/(?P<id>\d+)$', HomeViews.EditarVenta),
    url(r'^Registrar_pedido/(?P<id>\d+)$', HomeViews.Registrar_pedido),
    url(r'^EditarCompra/(?P<id>\d+)$', HomeViews.EditarCompra),
    url(r'^EditarTransaccion/(?P<id>\d+)$', HomeViews.EditarTransaccion),
    url(r'^Factura/(?P<id>\d+)$', HomeViews.Factura),
    url(r'^Facturar/(?P<id>\d+)$', HomeViews.Facturar),
    url(r'^Registrar/(?P<id>\d+)$', HomeViews.Registrar),
    url(r'^EditarPedido/(?P<id>\d+)$', HomeViews.EditarPedido),
    url(r'^get_form/(?P<object>[a-zA-z]+)/(?P<id>\d+)$', HomeViews.get_form),
    url(r'^get_form/(?P<id>\d+)$', HomeViews.get_form),
    url(r'^editar/(?P<object>[a-zA-z]+)/(?P<id>\d+)$', HomeViews.editar),
    url(r'^eliminar/(?P<object>[a-zA-z]+)/(?P<id>\d+)$', HomeViews.eliminar),
)

Home/forms.py
# -*- coding: utf-8 -*-
import re
from django import forms
from django.forms import ModelForm
from models import *
from django.forms import TextInput

from Jagu import settings

class LoginForm(forms.Form):
    """
    Formulario para login
    """
    username = forms.CharField(label=u'Nombre de usuario', widget=forms.TextInput(attrs={'placeholder': 'Usuario'}),
                               required=True)
    password = forms.CharField(label=u'Contraseña',
                               widget=forms.PasswordInput(render_value=False, attrs={'placeholder': 'Password'}),
                               required=True)


class RegistrationForm(forms.Form):
    """
    Formulario para el registro de usuarios
    """
    nickname = forms.CharField(max_length=50, label=u'Nombre de usuario', widget=forms.TextInput(attrs={'class': ''}),
                                required=True)
    nombre = forms.CharField(max_length=50, label=u'Nombre', widget=forms.TextInput(attrs={'class': ''}),
                                required=True)
    apellido = forms.CharField(max_length=50, label=u'Apellido', widget=forms.TextInput(attrs={'class': ''}),
                                required=True)
    email = forms.EmailField(label=u'Correo Electrónico', max_length=50, widget= forms.TextInput(attrs={'class': ''}),
                                 required=True)
    password = forms.CharField(label=u'Contraseña', widget=forms.PasswordInput(render_value=False, attrs={'class': ''}),
                                required=True)
    cpassword = forms.CharField(label=u'Verificar contraseña',
                                widget=forms.PasswordInput(render_value=False, attrs={'class': ''}),
                                required=True)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

    def clean(self):
        if Usuario.objects.filter(email=self.cleaned_data['email']).count():
            raise forms.ValidationError(u'El correo no se encuentra disponible')

        if Usuario.objects.filter(username=self.cleaned_data['nickname']).count():
            raise forms.ValidationError(u'El nombre de usuario no se encuentra disponible')
        else:
            if not Usuario.objects.nombre_usuario_valido(self.cleaned_data['nickname']):
                raise forms.ValidationError(u'El nombre de usuario introducido no tiene un formato correcto')

        if len(self.cleaned_data['password']) < 6 or len(self.cleaned_data['password']) > 15 or re.match('^[\w\.-]+$',self.cleaned_data['password']) is None:
            raise forms.ValidationError(u'Las contrasenas deben tener entre 6 y 15 caracteres. Intentelo nuevamente')

        if self.cleaned_data['password'] != self.cleaned_data['cpassword']:
            raise forms.ValidationError(u'Las contrasenas son distintas. Intentelo nuevamente')
        return self.cleaned_data


class monedaForm(ModelForm):
    class Meta:
        model = Moneda
        fields = ['divisa']

    def __init__(self, *args, **kwargs):
        super(monedaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class capitalesForm(ModelForm):
    class Meta:
        model = Capitales
        fields = ['cantidad','divisa']

    def __init__(self, *args, **kwargs):
        super(capitalesForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class transaccionesForm(ModelForm):
    class Meta:
        model = Transaccion
        fields = ['tipo','monto','divisa','descripcion','cliente']

    def __init__(self, *args, **kwargs):
        super(transaccionesForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class clienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['Nombre','Apellido','Cedula','Direccion','Telefono','Correo','Pseudonimo_MercadoLibre']

    def __init__(self, *args, **kwargs):
        super(clienteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class articuloForm(ModelForm):
    class Meta:
        model = Articulo
        fields = ['modelo','costo','peso','precio','categoria','marca','cantidad']

    def __init__(self, *args, **kwargs):
        super(articuloForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class pedidoForm(ModelForm):
    class Meta:
        model = Pedido
        fields = ['fechaCompra','fechaRecepcion','costoReal','fechaEsRecepcion','divisa','costoTotal','pesoTotal','costoEstimado','costoReal']

    def __init__(self, *args, **kwargs):
        super(pedidoForm, self).__init__(*args, **kwargs)
        self.fields['costoTotal'].widget = TextInput(attrs={'readonly': True})
        self.fields['pesoTotal'].widget = TextInput(attrs={'readonly': True})
        self.fields['costoEstimado'].widget = TextInput(attrs={'readonly': True})
        self.fields['fechaEsRecepcion'].widget = TextInput(attrs={'readonly': True})

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['fechaCompra'].widget = TextInput(attrs={'class': 'form-control datepicker'})
        self.fields['fechaRecepcion'].widget = TextInput(attrs={'class': 'form-control datepicker'})


class pedidoLineaForm(ModelForm):
    class Meta:
        model = LineaPedido
        fields = ['articulo','cantidad']

    def __init__(self, *args, **kwargs):
        super(pedidoLineaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class transaccionVentaForm(ModelForm):
    class Meta:
        model = Transaccion
        fields = ['divisa','cliente']

    def __init__(self, *args, **kwargs):
        super(transaccionVentaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class transaccionCompraDivisa(ModelForm):
    class Meta:
        model = Transaccion
        fields = ['monto']

    def __init__(self, *args, **kwargs):
        super(transaccionCompraDivisa, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class lineaDivisaForm(ModelForm):
    class Meta:
        model = LineaDivisa
        fields = ['divisa_compra','cantidad']

    def __init__(self, *args, **kwargs):
        super(lineaDivisaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class lineaVentaForm(ModelForm):
    class Meta:
        model = LineaVenta
        fields = ['articulo','cantidad']

    def __init__(self, *args, **kwargs):
        super(lineaVentaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class categoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = ['titulo','padre']

    def __init__(self, *args, **kwargs):
        super(categoriaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'



class marcaForm(ModelForm):
    class Meta:
        model = Marca
        fields = ['titulo']

    def __init__(self, *args, **kwargs):
        super(marcaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class caracteristicaForm(ModelForm):
    class Meta:
        model = Caracteristicas
        fields = ['titulo','descripcion']

    def __init__(self, *args, **kwargs):
        super(caracteristicaForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Jagusoft | {% block tittle %}{% endblock %}</title>
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Signika:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" media="screen" href="{{ STATIC_URL }}css/jquery-ui.min.css">
    <link rel="stylesheet" media="screen" href="{{ STATIC_URL }}css/library.css">
    {% block css %}{% endblock %}

    <script type="text/javascript" src="{{ STATIC_URL }}js/less.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
	<script type="text/javascript">
        $(document).ready(function(){
            {% block js %}{% endblock %}
            {% if msg %}
                $("#modalMsg").modal({show:true});
            {% endif %}
            $("#nueva_moneda").on('click',function(){
                $("#modalMoneda").modal({show:true});
            });
            $("#nueva_transaccion").on('click',function(){
                $("#modalTransaccion").modal({show:true});
            });
            $(".editObj").on('click',function(e){
                e.preventDefault();
                var objId = this.getAttribute('objId');
                var Type = this.getAttribute('Type');
                jQuery.ajax({
                    url: '/get_form/' + Type + '/' + objId,
                    type: "GET",
                    dataType: 'html',
                    success: function(data){
                        $("#editFormHtml").html(data);
                        $("#modalEditObj").modal({show:true});
                        $(".datepicker").datepicker();
                    }
                });
            });
            $(".modal-wide").on("show.bs.modal", function() {
              var height = $(window).height() - 250;
              $(this).find(".modal-body").css("max-height", height);
            });
            $(".datepicker").datepicker();
        });
        var enforceModalFocusFn = $.fn.modal.Constructor.prototype.enforceFocus;
        $.fn.modal.Constructor.prototype.enforceFocus = function() {};
	</script>
</head>
<body>
<div class="container">
    {% if usuario %}
        <div class="row">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                          data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/">Jagu</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="/NuevaVenta" class="" objId="0" Type="Venta">Venta</a></li>
                    <li><a href="/NuevaCompra" class="" objId="0" Type="Venta">Compra</a></li>
                    <li><a href="/NuevoPedido" class="" objId="0" Type="Venta">Pedido</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          Nuevo <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#" class="editObj" objId="0" Type="Transaccion">Nueva Transaccion</a></li>
                        <li><a href="#" class="editObj" objId="0" Type="Categoria">Nueva Categoria</a></li>
                        <li><a href="#" class="editObj" objId="0" Type="Marca">Nueva Marca</a></li>
                        <li><a href="#" class="editObj" objId="0" Type="Articulo">Nueva Articulo</a></li>
                        <li><a href="#" class="editObj" objId="0" Type="Cliente">Nuevo Cliente</a></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                          Admin <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="/Transacciones">Transacciones</a></li>
                        <li><a href="/Categorias">Categorias</a></li>
                        <li><a href="/Marcas">Marcas</a></li>
                        <li><a href="/Articulos">Articulos</a></li>
                        <li><a href="/Pedidos">Pedidos</a></li>
                        <li><a href="/Clientes">Clientes</a></li>
                      </ul>
                    </li>
                  </ul>
                  <form action="/Clientes" method="get" class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                      <input type="text" name="query" class="form-control" placeholder="Clientes">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                  </form>
                  <form action="/Articulos" method="get" class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                      <input type="text" name="query" class="form-control" placeholder="Articulos">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                  </form>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
        </div>
    {% endif %}
    <div class="row">
        {% block content %}{% endblock %}
    </div>
</div>
<div class="modal fade" id="modalMsg" tabindex="-1" role="dialog" aria-labelledby="modalMsg" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Mensaje del sistema</h3>
            </div>
            <div class="modal-body">
                    {{ msg }}
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true" type="button" href="#">
                    Aceptar
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal modal-wide fade" id="modalEditObj" tabindex="-1" role="dialog"
     aria-labelledby="modalEditObj" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Ingreso de datos</h3>
            </div>
            <div id="editFormHtml"></div>
        </div>
    </div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block js %}
    $('#articulos_activos').on('click',function(){
        $(".active").removeClass("active");
        $( this ).parent().addClass("active");
        $('.rowItem').each(function(){
            var quantity = $( this ).attr("quantity")
            if(quantity > 0){
                $( this ).show(500);
            }else{
                $( this ).hide(500);
            }
        });
    });
    $('#articulos_todos').on('click',function(){
        $(".active").removeClass("active");
        $( this ).parent().addClass("active");
        $('.rowItem').each(function(){
            $( this ).show( 500 );
        });
    });
{% endblock %}
{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Datos del capital</h3>
    </div>
    <div class="panel-body">
        <div class=" col-md-12">
            <div class="col-md-6 divider-vertical">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                                <div class="col-md-3">
                                    Ganancias Mes
                                </div>
                                <div class="col-md-3">
                                    {{ TT }}
                                </div>
                                <div class="col-md-3">
                                    Ganancias DE
                                </div>
                                <div class="col-md-3">
                                    <strong>{{ DE }}</strong>
                                </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                                <div class="col-md-3">
                                    Simadi
                                </div>
                                <div class="col-md-3">
                                    <strong>{{ simadi }}</strong>
                                </div>
                                <div class="col-md-3">
                                    Dolar Negro
                                </div>
                                <div class="col-md-3">
                                    <strong>{{ negro }}</strong>
                                </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                                <div class="col-md-3">
                                    Capital total
                                </div>
                                <div class="col-md-9">
                                    <strong>{{ Capital_total }}</strong>
                                </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-4">
                                Divisa
                            </div>
                            <div class="col-md-4">
                                Cantidad
                            </div>
                            <div class="col-md-4">
                                Costo Promedio
                            </div>
                        </div>
                    </li>
                    {% for a in Caps %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-4">
                                    {{ a.get_divisa_display  }}
                                </div>
                                <div class="col-md-4">
                                    <strong>{{ a.cantidad }}</strong>
                                </div>
                                <div class="col-md-4">
                                    {{ a.costo_promedio }}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
    <div class="no-gutter">

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Pedidos</h3>
    </div>
    <div class="panel-body">
        <div class=" col-md-12">
            <div class="moneda no-gutter">
                <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-1">
                                    Pagado
                                </div>
                                <div class="col-md-1">
                                    CostoT,
                                </div>
                                <div class="col-md-2">
                                    Fecha de Compra
                                </div>
                                <div class="col-md-2">
                                    Fecha Est. Recep.
                                </div>
                                <div class="col-md-2">
                                    Fecha de Recepcion
                                </div>
                                <div class="col-md-1">
                                    Peso
                                </div>
                                <div class="col-md-1">
                                    Costo Est
                                </div>
                                <div class="col-md-2">
                                    CostoReal
                                </div>
                            </div>
                        </li>
                    {% for m in pedidos %}
                        <li class="list-group-item">
                            <div class="row">
                                <a href="/EditarPedido/{{ m.id }}" Type="Pedido">
                                    <div class="col-md-1">
                                        {% if m.pagado %}
                                            Si
                                        {% else %}
                                            No
                                        {% endif %}
                                    </div>
                                    <div class="col-md-1">
                                        {{ m.costoTotal}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.fechaCompra}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.fechaEsRecepcion}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.fechaRecepcion}}
                                    </div>
                                    <div class="col-md-1">
                                        {{ m.pesoTotal}}
                                    </div>
                                    <div class="col-md-1">
                                        {{ m.costoEstimado}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.costoReal}}
                                    </div>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Transacciones</h3>
    </div>
    <div class="panel-body">
        <div class=" col-md-12">
            <div class="transacciones">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-7">
                                Motivo
                            </div>
                            <div class="col-md-1">
                                Tipo
                            </div>
                            <div class="col-md-2">
                                Monto
                            </div>
                            <div class="col-md-2">
                                Divisa
                            </div>
                        </div>
                    </li>
                    {% for m in transacciones %}
                        <li class="list-group-item">
                            <div class="row">
                                <a href="/EditarTransaccion/{{ m.id }}">
                                    <div class="col-md-7">
                                        {{ m.descripcion}}
                                    </div>
                                    <div class="col-md-1">
                                        {{ m.get_tipo_display}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.monto}}
                                    </div>
                                    <div class="col-md-2">
                                        {{ m.get_divisa_display }}
                                    </div>
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

templates/registro.html
{% extends 'base.html' %}
{% block title %}Registro {% endblock %}
{% block extrajs %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/varios.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/nod.js"></script>
{% endblock %}
{% block js %}
    $("#chkNotif").hide();
    $("#id_tipo").change(function(e){
        e.preventDefault();
        if ($(this).val() == 'AB'){
            $("#chkNotif").show();
        }else{
            $("#chkNotif").hide();
        }
    });
    $('#id_fecha_nacimiento').datepicker({
        format: 'dd/mm/yyyy',
        language:'es'
    });
    $("#id_tipo").select2();
    $("#id_nombre").keypress(function(event) {
        return restringeCaracteres(this, event, {expreg:/([A-Z,a-z,\s])/});
    });
    $("#id_apellido").keypress(function(event) {
        return restringeCaracteres(this, event, {expreg:/([A-Z,a-z,\s])/});
    });
    $("#id_nickname").keypress(function(event) {
        return restringeCaracteres(this, event, {expreg:/([A-Z,a-z,0-9,\-,_])/});
    });

    var r_metrics = [
          [ '#id_nickname', 'presence', 'Indique su nombre de usuario' ],
          [ '#id_nombre', 'presence', 'Indique su nombre' ],
          [ '#id_apellido', 'presence', 'Indique su apellido' ],
          [ '#id_password', 'presence', 'Indique su contraseña' ],
          [ '#id_cpassword', 'presence', 'Repita la contraseña' ],
          [ '#id_email','presence', 'Indique su correo' ],
          [ '#id_email','email','Ingrese un correo válido' ],
          [ '#id_tipo','presence','Debe seleccionar el tipo de usuario' ],

    ];
    $('#registrar-form').nod(r_metrics);
    $('#guardar').on('click',function(){
        $('#registrar-form input[type=text]').each(function(n,element){
            if ($(element).val()=='') {
                alert('introduzca '+element.name+'');
                return false;
            }
        });
        return true;
    });

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-4">
            {% if user.is_authenticated %}
                <p><h4>Superadmin</h4></p>
            {% endif %}
            <p><h4>Nuevo Usuario</h4></p>
            <form action="/registro/" method="post" class="form-vertical" id="registrar-form">
                <ul class="messages">
                {% for field in registrationForm.non_field_errors %}
                     <li>{{ field }}</li>
                {% endfor %}
                </ul>

                {% csrf_token %}
                {% for r in registrationForm %}
                <div class="form-group">
                    <label class="control-label">{{ r.label }}</label>
                    <div class="controls">
                        {{ r }}
                    </div>
                </div>
                {% endfor %}
                <div class="form-group" id="chkNotif">
                <input name="notif" value="1" type="checkbox"> ¿Desea recibir notificaciones? <br>
                    <input name="gestoria" value="1" type="checkbox"> ¿Desea salir en el listado de gestoría?
                </div>
                <button class="btn btn-info" type="submit" id="guardar">Guardar</button>
            </form>
        </div>
    </div>
</div>
    
{% endblock %}